services:
  mysql:
    image: 'mysql:8.0.41'
    environment:
      - 'MYSQL_DATABASE=${DB_DATABASE}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=${DB_USERNAME}'
    ports:
      - '3306'
